---
inputs:
- type: git
  branch: master
  service: ${GIT_REPO}
  path: .tekton
triggers:
- type: git
  name: Git PR Trigger
  service: ${GIT_REPO}
  branch: master
  events: {"push":true,"pull_request":true,"pull_request_closed":false}
  eventListener: listener
- type: manual
  name: Manual Trigger
  eventListener: listener
properties:
- name: REGISTRY_REGION
  value: ${REGISTRY_REGION_ID}
  type: text
- name: REGISTRY_NAMESPACE
  value: ${REGISTRY_NAMESPACE}
  type: text
- name: DEVOPS_BUILD_SIGNER
  value: ${BUILD_SIGNER}
  type: text
- name: DEVOPS_VALIDATION_SIGNER
  value: ${VALIDATION_SIGNER}
  type: text
- name: IBMCLOUD_TARGET_REGION
  value: ${BUILD_REGION_ID}
  type: text
- name: VAULT_INSTANCE
  value: ${VAULT_INSTANCE}
  type: text
