apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: apikey
        description: the ibmcloud api key
      - name: api
        description: the ibmcloud api endpoint
        default: "https://cloud.ibm.com"
      - name: registryNamespace
        description: the ibmcloud registry namespace
      - name: imageName
        description: the base image name
        default: "hello-containers-tekton"
      - name: registryRegion
        description: the ibmcloud registry region     
      - name: vaultName
        description: The Key Protect instance name
      - name: buildSigner
        description: The build signer name
      - name: validationSigner
        description: The validation signer name
      - name: resourceGroup
        description: The resource group   
  steps:
    - name: clone-repo
      image: alpine/git
      env:
        - name: REPOSITORY
          value: $(inputs.params.repository)
        - name: REVISION
          value: $(inputs.params.revision)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo "Cloning $REPOSITORY";
          git clone -q -b $REVISION $REPOSITORY .;
    - name: build-docker-image
      image: ibmcom/pipeline-base-image
      env:
        - name: IBM_CLOUD_API_KEY
          value: $(inputs.params.apikey)
        - name: API
          value: $(inputs.params.api)
        - name: REGION
          value: $(inputs.params.registryRegion)
        - name: HOME
          value: "/root"
        - name: REGISTRY_NAMESPACE
          value: $(inputs.params.registryNamespace)
        - name: VAULT_INSTANCE
          value: $(inputs.params.vaultInstance)
        - name: BUILD_SIGNER
          value: $(inputs.params.buildSigner)
        - name: VALIDATION_SIGNER
          value: $(inputs.params.validationSigner)
        - name: validationSigner
          value: $(params.validationSigner)
        - name: resourceGroup
          value: $(params.resourceGroup)
        - name: IMAGE_NAME
          value: $(inputs.params.imageName)
        - name: ARCHIVE_DIR
          value: "/artifacts"
        - name: BUILD_NUMBER
          value: "0"
        - name: GIT_BRANCH
          value: $(inputs.params.revision)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
           #!/bin/bash
          echo "TEST INPUT VAULES";
          echo "$REGISTRY_NAMESPACE";
          echo "$IBMCLOUD_API_KEY";
          echo "$API";
          echo "$VAULT_INSTANCE";
          echo "$BUILD_SIGNER";
          source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/image_signing/add_docker.sh")
          # Restore root & repository keys
          if [ -z "$VAULT_INSTANCE" ]; then
            echo "No op"
          else
            export IBMCLOUD_API_KEY=$IBM_CLOUD_API_KEY
            export IBMCLOUD_TARGET_REGION=${IBMCLOUD_TARGET_REGION:-"eu-gb"}

            # if target region is in the 'ibm:yp:<region>' just keep the region part
            REGION_SUBSET=$(echo "$IBMCLOUD_TARGET_REGION" | awk -F ':' '{print $3;}')
            if [[ -z "$REGION_SUBSET" ]]; then
              echo "IBM Cloud Target Region is $IBMCLOUD_TARGET_REGION"
            else
              export IBMCLOUD_TARGET_REGION=$REGION_SUBSET
              echo "IBM Cloud Target Region is $IBMCLOUD_TARGET_REGION. export IBMCLOUD_TARGET_REGION=$REGION_SUBSET done"
            fi

            ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r "$IBMCLOUD_TARGET_REGION"
            
            DEVOPS_SIGNER="$BUILD_SIGNER"
            source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/image_signing/signing_utils.sh")
            source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/image_signing/create_signer.sh")
          fi
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
      
